cookie:
  expiry_days: 30
  key: MasterChief
  name: loginCookie
credentials:
  usernames:
    admin2:
      email: ifeanyi123igweze@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Ifeanyi Christopher Igweze
      password: $2b$12$HhvQStBbbXrAsS9woedN/.FijS05ufrHumglvOPjYWp0uv0PhJHcu
    eb:
      email: olaleyefiyin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Elizabeth Olaleye
      password: $2b$12$xOyktBKAMTvfswt3r/dW1evHAdd36bLsAKS5lcZcK3.SjfxtnSa4m
    hboy:
      email: CIStimetableofficer@covenantuniversity.edu.ng
      failed_login_attempts: 0
      logged_in: false
      name: Honour Adewunmi
      password: $2b$12$QLK5sJyV.2xx3mX.gJezOulphpsRTzWakvfXid1SnHebUSdXenclq
    honourboy:
      email: honouradewunmi12@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Mayowa Adewunmi
      password: $2b$12$CI/qPBYEAFOXK88.8A46ueBO0dn1BozdJJ8zMo53X.mq8fDdk3tA2
    jd:
      email: fizzybabz456@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: john
      password: $2b$12$iHTAM3EptomGYXmiH9BAqeKubaJxqXLkirGn/rRlpj9JzuYIGj.8i
    masterchief:
      email: mcphilo100@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Test Update
      password: $2b$12$qQ/C21FuX8aIheKp6nkseerI8h2n7GUeuFMDECL7u2yhDDXrog5A.
    tesfaye:
      email: fisayobabz@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Fisayo Babatunde
      password: $2b$12$PR9TeTNmmds4wpfdqEBrP.UR984g6YPMXkKQTqfG1L.E1nz.Fi0mO
pre-authorized:
  emails:
  - timetableofficer@covenantuniversity.edu.ng
