cookie:
  expiry_days: 30
  key: MasterChief
  name: loginCookie
credentials:
  usernames:
    hboy:
      email: CIStimetableofficer@covenantuniversity.edu.ng
      failed_login_attempts: 0
      logged_in: false
      name: Honour Adewunmi
      password: $2b$12$QLK5sJyV.2xx3mX.gJezOulphpsRTzWakvfXid1SnHebUSdXenclq
    masterchief:
      email: timetableofficer@covenantuniversity.edu.ng
      failed_login_attempts: 0
      logged_in: false
      name: Ifeanyi Igweze
      password: admin
pre-authorized:
  emails:
  - timetableofficer@covenantuniversity.edu.ng
